# Generated by Django 3.1.4 on 2021-04-07 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='heartdata',
            name='owner',
        ),
    ]
