# Generated by Django 3.1.4 on 2021-04-09 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0005_heartdata_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorHospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(max_length=25)),
                ('hospital_name', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254)),
                ('phone_no', models.IntegerField()),
                ('Location', models.CharField(max_length=25)),
            ],
        ),
    ]
